image: gitlab.devartis.com:4567/devops/image-utils:python-base

stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: ./.pip-cache
  PYTHON_VENV_DIR: ./.env
  DJANGO_SETTINGS_MODULE: project_name.settings.testing
  PYTHON_SCRIPT: python3
  NODE_MODULES_DIR: ./node_modules

build_js:
  stage: build
  cache:
    paths:
      - $NODE_MODULES_DIR
  artifacts:
    paths:
      - $NODE_MODULES_DIR
  script: npm install

build:
  stage: build
  cache:
    paths:
      - $PIP_CACHE_DIR
      - $PYTHON_VENV_DIR
  artifacts:
    paths:
      - $PIP_CACHE_DIR
      - $PYTHON_VENV_DIR
  script:
    - $PYTHON_SCRIPT -m venv $PYTHON_VENV_DIR
    - source $PYTHON_VENV_DIR/bin/activate
    - pip install -r requirements/testing.txt --cache-dir $PIP_CACHE_DIR

.test_template: &test_definition
  stage: test
  before_script:
    - source $PYTHON_VENV_DIR/bin/activate
  dependencies:
    - build

migration_test:
  <<: *test_definition
  script:
    - $PYTHON_SCRIPT manage.py migrate --settings=$DJANGO_SETTINGS_MODULE

django_tests:
  <<: *test_definition
  script: sh scripts/tests.sh

pylint:
  <<: *test_definition
  script: sh scripts/pylint.sh

pep8:
  image: gitlab.devartis.com:4567/devops/image-utils:pep8
  stage: test
  script: sh scripts/pep8.sh

jscpd:
  image: gitlab.devartis.com:4567/devops/image-utils:jscpd
  stage: test
  script: sh scripts/jscpd.sh

eslint:
  stage: test
  image: mhart/alpine-node:6.8.0
  script: sh scripts/eslint.sh
  dependencies:
    - build_js

deploy_testing:
  image: boomtownroi/git
  stage: deploy
  script: sh deployment/configure_cd_testing.sh
  environment: testing
  only:
    - master # Or default branch :)

deploy_staging:
  image: boomtownroi/git
  stage: deploy
  script: sh deployment/configure_cd_staging.sh
  environment: staging
  when: manual
  only:
    - master # Or default branch :)
