image: gitlab.devartis.com:4567/devops/image-utils:python-base

stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: ./.pip-cache
  PYTHON_VENV_DIR: ./.env
  DJANGO_SETTINGS_MODULE: conf.settings.testing
  PYTHON_SCRIPT: python3
  NODE_MODULES_DIR: ./node_modules

build_js:
  stage: build
  image: mhart/alpine-node:6.8.0
  cache:
    paths:
      - $NODE_MODULES_DIR
  artifacts:
    expire_in: "1 hrs"
    paths:
      - $NODE_MODULES_DIR
  script: npm install

build:
  stage: build
  cache:
    paths:
      - $PIP_CACHE_DIR
      - $PYTHON_VENV_DIR
  artifacts:
    expire_in: "1 hrs"
    paths:
      - $PIP_CACHE_DIR
      - $PYTHON_VENV_DIR
  script:
    - $PYTHON_SCRIPT -m venv $PYTHON_VENV_DIR
    - source $PYTHON_VENV_DIR/bin/activate
    - pip install -r requirements/testing.txt --cache-dir $PIP_CACHE_DIR

.test_template: &test_definition
  stage: test
  before_script:
    - source $PYTHON_VENV_DIR/bin/activate
  dependencies:
    - build

migration_test:
  <<: *test_definition
  script:
    - $PYTHON_SCRIPT manage.py migrate --settings=$DJANGO_SETTINGS_MODULE

tests:
  <<: *test_definition
  script: sh scripts/tests.sh

jscpd:
  image: gitlab.devartis.com:4567/devops/image-utils:jscpd
  stage: test
  script: sh scripts/jscpd.sh

eslint:
  stage: test
  image: mhart/alpine-node:6.8.0
  script: sh scripts/eslint.sh
  dependencies:
    - build_js

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=pompom-dev --api-key=$HEROKU_API_KEY
  only:
  - master

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=pompom-prod --api-key=$HEROKU_API_KEY
  when: manual
  only:
  - tags