# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 13:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.NullBooleanField(choices=[(True, 'Pass'), (False, 'Fallout'), (None, 'N/A')])),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='CardSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('contents', ckeditor.fields.RichTextField(verbose_name='contents')),
                ('is_gradable', models.BooleanField(verbose_name='is gradable')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='huddle_board.Card', verbose_name='card')),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='card_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='huddle_board.CardSection', verbose_name='card section'),
        ),
        migrations.AddField(
            model_name='answer',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='huddle_board.Observation', verbose_name='observation'),
        ),
    ]
