# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_board', '0002_auto_20170803_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='draw_pile',
            field=models.ManyToManyField(blank=True, to='huddle_board.Card', verbose_name='draw pile'),
        ),
    ]
