# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_board', '0005_auto_20170807_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('contents', models.TextField(verbose_name='contents')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='board',
            name='draw_pile',
        ),
        migrations.AddField(
            model_name='cardnote',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='huddle_board.Board', verbose_name='board'),
        ),
        migrations.AddField(
            model_name='cardnote',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='huddle_board.Card', verbose_name='card'),
        ),
    ]
