# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_board', '0006_auto_20170809_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='companion_image',
            field=models.ImageField(blank=True, null=True, upload_to='companion_images/', verbose_name='companion image'),
        ),
    ]
