# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 14:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_board', '0007_card_companion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('contents', ckeditor.fields.RichTextField(verbose_name='contents')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
    ]
