# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_board', '0008_safetymessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='huddle board password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
