# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_board', '0009_siteconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='board_password',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='board_passwords',
            field=models.TextField(blank=True, help_text='Multiple comma-separated values are allowed.', verbose_name='huddle board passwords'),
        ),
    ]
