# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_board', '0011_card_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsection',
            name='check_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='check count'),
        ),
    ]
