# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('huddle_board', '0012_cardsection_check_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name': 'tag',
            },
            bases=('taggit.tag',),
        ),
        migrations.AddField(
            model_name='answer',
            name='checks_done',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='checks done'),
        ),
    ]
