# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 17:25
from __future__ import unicode_literals

from django.db import migrations, models
from ..management.commands.fix_permissions import fix


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_board', '0013_auto_20170901_1325'),
    ]
    operations = [
        migrations.RunPython(fix),
    ]
